apiVersion: v1
kind: Pod
metadata:
  name: dt
  namespace: ai
  labels:
    name: dt
spec:
  containers:
  - name: dt
    image: jupyter/tensorflow-notebook:ubuntu-20.04
    ports:
      - containerPort: 8888
        hostPort: 10001
        protocol: TCP
    volumeMounts:
      - name: nfs-pvc
        mountPath: /home/jovyan/work
  volumes: 
    - name: nfs-pvc
      nfs:
          path: /home/kyokoz/data/Supervised Learning:Decision Tree
          server: 192.168.100.100
