apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  namespace: kube-nfs #replace by the namespace of provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs-client-provisioner
            - name: NFS_SERVER
              value: 192.168.100.100 #replace by the IP address of NFS server
            - name: NFS_PATH
              value: /home/kyokoz/data #replace by the path of NFS directory
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.100.100 #replace by the IP address of NFS server
            path: /home/kyokoz/data #replace by the path of NFS directory
