apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: kube-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage-class
  nfs:
    path: /home/kyokoz/data
    server: 192.168.100.100
